const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const token=()=>localStorage.getItem('bizkit_token')||''; const user=()=>JSON.parse(localStorage.getItem('bizkit_user')||'null');
const money=v=>'₹'+Math.round(Number(v)||0).toLocaleString('en-IN');
function headers(){return {'Content-Type':'application/json',...(token()?{'Authorization':'Bearer '+token()}:{})}}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function logout(){localStorage.removeItem('bizkit_token');localStorage.removeItem('bizkit_user');location.href='/login'}
function requireAuth(){if(!token()){location.href='/login?next='+encodeURIComponent(location.pathname);return false}return true}
function setUser(){const u=user();$$('[data-user-name]').forEach(x=>x.textContent=u?.name||'');$$('[data-business]').forEach(x=>x.textContent=u?.name||'Your business')}
function activeNav(){const p=location.pathname;$$('.side a[data-route]').forEach(a=>a.classList.toggle('active',p===a.dataset.route || (a.dataset.route!=='/app'&&p.startsWith(a.dataset.route))))}
function initShell(){setUser();activeNav();const q=$('#globalSearch');if(q){let timer;q.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const v=q.value.trim();if(v.length<2)return;const d=await api('/api/search?q='+encodeURIComponent(v));const box=$('#searchResults');if(!box)return;const all=[...d.customers.map(x=>({t:'Customer',n:x.name,u:'/app/customers?id='+x.id})),...d.products.map(x=>({t:'Product',n:x.name,u:'/app/products?id='+x.id})),...d.invoices.map(x=>({t:'Invoice',n:x.invoice_no,u:'/app/invoices?id='+x.id}))];box.innerHTML=all.length?all.map(x=>`<a href="${x.u}"><b>${escapeHtml(x.t)}</b> · ${escapeHtml(x.n)}</a>`).join(''):'<div style="padding:12px;color:var(--muted)">No results</div>';box.classList.add('show')},250)});document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#searchResults')?.classList.remove('show')})}}
function wireAuth(){const form=$('#authForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const mode=form.dataset.mode;try{const body={email:$('#email').value,password:$('#password').value};if(mode==='signup')body.name=$('#name').value;const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('bizkit_token',d.token);localStorage.setItem('bizkit_user',JSON.stringify(d.user));location.href=new URLSearchParams(location.search).get('next')||'/app'}catch(err){$('#formError').textContent=err.message;$('#formError').hidden=false}})}
async function dashboard(){if(!requireAuth())return;const d=await api('/api/dashboard');$('#rev').textContent=money(d.revenue);$('#outstanding').textContent=money(d.outstanding);$('#expenses').textContent=money(d.totalExpenses);$('#profit').textContent=money(d.profitEstimate);$('#customers').textContent=d.customers;$('#lowStock').textContent=d.lowStock;const acts=$('#activity');acts.innerHTML=d.recent?.length?d.recent.map(a=>`<div class="activityItem"><span class="dot"></span><div><strong>${escapeHtml(a.title)}</strong><small>${new Date(a.created_at).toLocaleString()}</small></div></div>`).join(''):'<div class="empty">No activity yet.</div>';loadSummaryChart()}
async function loadSummaryChart(){const d=await api('/api/reports/summary');const box=$('#salesChart');if(!box)return;const max=Math.max(1,...d.months.map(x=>Number(x.sales)));box.innerHTML=d.months.map(x=>`<div class="barWrap"><div class="bar" style="height:${Math.max(4,Number(x.sales)/max*180)}px"></div><div class="barLabel">${x.month.slice(5)}</div></div>`).join('')}
async function listCustomers(){if(!requireAuth())return;const d=await api('/api/customers');$('#customerRows').innerHTML=d.customers.length?d.customers.map(c=>`<tr><td><a href="/app/customers?id=${c.id}"><b>${escapeHtml(c.name)}</b></a></td><td>${escapeHtml(c.phone||'-')}</td><td>${escapeHtml(c.email||'-')}</td><td>${escapeHtml(c.gstin||'-')}</td><td><button class="btn sm danger" onclick="deleteCustomer(${c.id})">Delete</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No customers yet.</div></td></tr>'}
async function deleteCustomer(id){if(confirm('Delete this customer?')){await api('/api/customers/'+id,{method:'DELETE'});toast('Customer deleted');listCustomers()}}
async function customerDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/customers/'+id);$('#customerName').textContent=d.customer.name;$('#customerPhone').textContent=d.customer.phone||'-';$('#customerEmail').textContent=d.customer.email||'-';$('#customerAddress').textContent=d.customer.address||'-';$('#customerGstin').textContent=d.customer.gstin||'-';const total=d.invoices.reduce((a,x)=>a+Number(x.total||0),0),paid=d.payments.reduce((a,x)=>a+Number(x.amount||0),0);$('#customerOutstanding').textContent=money(Math.max(0,total-paid));$('#customerInvoices').innerHTML=d.invoices.length?d.invoices.map(x=>`<tr><td><a href="/app/invoices?id=${x.id}"><b>${x.invoice_no}</b></a></td><td>${x.invoice_date||'-'}</td><td>${money(x.total)}</td><td><span class="pill ${x.status==='paid'?'':'amber'}">${x.status}</span></td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No invoices.</div></td></tr>';$('#customerPayments').innerHTML=d.payments.length?d.payments.map(x=>`<tr><td>${x.paid_at||'-'}</td><td>${money(x.amount)}</td><td>${escapeHtml(x.method)}</td><td>${escapeHtml(x.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No payments.</div></td></tr>'}
async function listProducts(){if(!requireAuth())return;const d=await api('/api/products');$('#productRows').innerHTML=d.products.length?d.products.map(p=>`<tr><td><a href="/app/products?id=${p.id}"><b>${escapeHtml(p.name)}</b></a></td><td>${escapeHtml(p.sku||'-')}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.gst_rate}%</td><td>${p.stock<=p.low_stock_threshold?'<span class="pill red">Low</span>':'<span class="pill">OK</span>'}</td><td><button class="btn sm" onclick="adjustStock(${p.id},'in')">+ Stock</button> <button class="btn sm" onclick="adjustStock(${p.id},'out')">- Stock</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty">No products yet.</div></td></tr>'}
async function adjustStock(id,type){const q=prompt(`Quantity to ${type==='in'?'add':'remove'}:`);if(!q)return;await api('/api/products/'+id+'/adjust-stock',{method:'POST',body:JSON.stringify({quantity:Number(q),type,note:'Manual adjustment'})});toast('Stock updated');listProducts()}
async function productDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/products/'+id);$('#productName').textContent=d.product.name;$('#productSku').textContent=d.product.sku||'-';$('#productStock').textContent=d.product.stock;$('#productPrice').textContent=money(d.product.price);$('#productGst').textContent=d.product.gst_rate+'%';$('#movements').innerHTML=d.movements.length?d.movements.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString()}</td><td>${m.quantity}</td><td>${escapeHtml(m.type)}</td><td>${escapeHtml(m.note||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No stock movements.</div></td></tr>'}
async function listInvoices(){if(!requireAuth())return;const d=await api('/api/invoices');$('#invoiceRows').innerHTML=d.invoices.length?d.invoices.map(x=>`<tr><td><a href="/app/invoices?id=${x.id}"><b>${escapeHtml(x.invoice_no)}</b></a></td><td>${escapeHtml(x.customer_name||'-')}</td><td>${x.invoice_date||'-'}</td><td>${money(x.total)}</td><td><span class="pill ${x.status==='paid'?'':'amber'}">${x.status}</span></td><td><button class="btn sm" onclick="markInvoicePaid(${x.id})">Mark paid</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No invoices yet.</div></td></tr>'}
async function markInvoicePaid(id){await api('/api/invoices/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:'paid'})});toast('Invoice marked paid');listInvoices()}
async function invoiceDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/invoices/'+id);const i=d.invoice;$('#invoiceTitle').textContent=i.invoice_no;$('#invoiceCustomer').textContent=i.customer_name||'-';$('#invoiceDate').textContent=i.invoice_date||'-';$('#invoiceDue').textContent=i.due_date||'-';$('#invoiceTotal').textContent=money(i.total);$('#invoiceStatus').textContent=i.status;$('#invoiceItems').innerHTML=(i.items||[]).map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${x.qty}</td><td>${money(x.rate)}</td><td>${money(x.amount)}</td></tr>`).join('');$('#paymentRows').innerHTML=d.payments.length?d.payments.map(p=>`<tr><td>${p.paid_at||'-'}</td><td>${money(p.amount)}</td><td>${escapeHtml(p.method)}</td><td>${escapeHtml(p.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No payments recorded.</div></td></tr>';window.currentInvoice=d}
async function listPayments(){if(!requireAuth())return;const d=await api('/api/payments');$('#paymentRowsMain').innerHTML=d.payments.length?d.payments.map(p=>`<tr><td>${p.paid_at||'-'}</td><td>${escapeHtml(p.customer_name||'-')}</td><td>${escapeHtml(p.invoice_no||'-')}</td><td>${money(p.amount)}</td><td>${escapeHtml(p.method)}</td><td>${escapeHtml(p.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No payments yet.</div></td></tr>'}
async function listExpenses(){if(!requireAuth())return;const d=await api('/api/expenses');$('#expenseRows').innerHTML=d.expenses.length?d.expenses.map(x=>`<tr><td>${x.expense_date||'-'}</td><td>${escapeHtml(x.category)}</td><td>${money(x.amount)}</td><td>${escapeHtml(x.note||'-')}</td><td><button class="btn sm danger" onclick="deleteExpense(${x.id})">Delete</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No expenses yet.</div></td></tr>'}
async function deleteExpense(id){if(confirm('Delete expense?')){await api('/api/expenses/'+id,{method:'DELETE'});toast('Expense deleted');listExpenses()}}
async function listPurchases(){if(!requireAuth())return;const d=await api('/api/purchases');$('#purchaseRows').innerHTML=d.purchases.length?d.purchases.map(x=>`<tr><td>${escapeHtml(x.purchase_no)}</td><td>${escapeHtml(x.supplier_name||'-')}</td><td>${x.purchase_date||'-'}</td><td>${money(x.total)}</td><td>${escapeHtml(x.status)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No purchases yet.</div></td></tr>'}
async function listSuppliers(){if(!requireAuth())return;const d=await api('/api/suppliers');$('#supplierRows').innerHTML=d.suppliers.length?d.suppliers.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.phone||'-')}</td><td>${escapeHtml(x.email||'-')}</td><td>${escapeHtml(x.gstin||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No suppliers yet.</div></td></tr>'}
async function reports(){if(!requireAuth())return;const d=await api('/api/reports/summary');const totals=d.months.reduce((a,x)=>{a.s+=Number(x.sales);a.e+=Number(x.expenses);return a},{s:0,e:0});$('#repSales').textContent=money(totals.s);$('#repExpenses').textContent=money(totals.e);$('#repProfit').textContent=money(totals.s-totals.e);const max=Math.max(1,...d.months.map(x=>Number(x.sales)));$('#reportChart').innerHTML=d.months.map(x=>`<div class="barWrap"><div class="bar" style="height:${Math.max(5,Number(x.sales)/max*180)}px"></div><div class="barLabel">${x.month}</div></div>`).join('')}
async function settings(){if(!requireAuth())return;const d=await api('/api/profile');const p=d.profile||{};for(const [id,val] of Object.entries({businessName:p.businessName||'',businessType:p.businessType||'Services',phone:p.phone||'',email:p.email||'',gstin:p.gstin||'',state:p.state||'',address:p.address||'',currency:p.currency||'INR'})){const el=$('#set_'+id);if(el)el.value=val}const s=await api('/api/integrations/status');$('#rzStatus').textContent=s.razorpay?'Configured':'Not configured';$('#waStatus').textContent=s.whatsapp?'Configured':'Not configured';$('#mailStatus').textContent=s.email?'Configured':'Not configured'}
function toolInit(){if(!requireAuth())return;const forms={gst:['gstMode','gstAmount','gstRate'],profit:['cost','sell'],break:['fixed','price','variable'],salary:['ctc','bonus','pf','other']};function calc(id){if(id==='gst'){const a=n($('#gstAmount').value),r=n($('#gstRate').value);if($('#gstMode').value==='add'){const tax=a*r/100;$('#gstRes').textContent=`Base ${money(a)} · GST ${money(tax)} · Total ${money(a+tax)}`}else{const base=a/(1+r/100),tax=a-base;$('#gstRes').textContent=`Base ${money(base)} · GST ${money(tax)} · Total ${money(a)}`}}if(id==='profit'){const c=n($('#cost').value),s=n($('#sell').value),p=s-c;$('#profitRes').textContent=`Profit ${money(p)} · Margin ${(s?p/s*100:0).toFixed(1)}% · Markup ${(c?p/c*100:0).toFixed(1)}%`}if(id==='break'){const f=n($('#fixed').value),p=n($('#price').value),v=n($('#variable').value),m=p-v;$('#breakRes').textContent=m>0?`Break-even ${Math.ceil(f/m)} units · Sales ${money(Math.ceil(f/m)*p)}`:'Selling price must exceed variable cost'}if(id==='salary'){const c=n($('#ctc').value),b=n($('#bonus').value),pf=n($('#pf').value),o=n($('#other').value),g=(c-b)/12;$('#salaryRes').textContent=`Monthly gross ${money(g)} · Estimated take-home ${money(Math.max(0,g-pf-o))}`}}$$('[data-calc]').forEach(b=>b.onclick=()=>calc(b.dataset.calc))}
async function integrations(){if(!requireAuth())return;const d=await api('/api/integrations/status');$('#rzStatus').textContent=d.razorpay?'Connected':'Not configured';$('#waStatus').textContent=d.whatsapp?'Connected':'Not configured';$('#mailStatus').textContent=d.email?'Connected':'Not configured'}
async function saveProfile(){const b={businessName:$('#set_businessName').value,businessType:$('#set_businessType').value,phone:$('#set_phone').value,email:$('#set_email').value,gstin:$('#set_gstin').value,state:$('#set_state').value,address:$('#set_address').value,currency:$('#set_currency').value};await api('/api/profile',{method:'PUT',body:JSON.stringify(b)});toast('Business profile saved')}
async function submitCustomer(){const b={name:$('#c_name').value,phone:$('#c_phone').value,email:$('#c_email').value,address:$('#c_address').value,gstin:$('#c_gstin').value,notes:$('#c_notes').value};await api('/api/customers',{method:'POST',body:JSON.stringify(b)});toast('Customer created');location.href='/app/customers'}
async function submitProduct(){const b={name:$('#p_name').value,sku:$('#p_sku').value,hsnSac:$('#p_hsn').value,unit:$('#p_unit').value,price:n($('#p_price').value),purchasePrice:n($('#p_purchase').value),gstRate:n($('#p_gst').value),stock:n($('#p_stock').value),lowStockThreshold:n($('#p_low').value),trackStock:$('#p_track').checked};await api('/api/products',{method:'POST',body:JSON.stringify(b)});toast('Product added');location.href='/app/products'}
async function submitExpense(){await api('/api/expenses',{method:'POST',body:JSON.stringify({expenseDate:$('#e_date').value,category:$('#e_cat').value,amount:n($('#e_amount').value),note:$('#e_note').value})});toast('Expense added');location.href='/app/expenses'}
async function submitPayment(){await api('/api/payments',{method:'POST',body:JSON.stringify({invoiceId:$('#pay_invoice').value||null,customerId:$('#pay_customer').value||null,amount:n($('#pay_amount').value),method:$('#pay_method').value,reference:$('#pay_ref').value,paidAt:$('#pay_date').value,note:$('#pay_note').value})});toast('Payment recorded');location.href='/app/payments'}
async function createPaymentLink(){const d=await api('/api/integrations/razorpay/payment-link',{method:'POST',body:JSON.stringify({amount:n($('#pl_amount').value),customerName:$('#pl_name').value,customerPhone:$('#pl_phone').value,customerEmail:$('#pl_email').value,referenceId:$('#pl_ref').value,description:$('#pl_desc').value})});$('#linkResult').innerHTML=`<div class="success">Payment link created: <a href="${d.short_url}" target="_blank"><b>${d.short_url}</b></a></div>`}
function openPrint(){window.print()}
window.Biz={api,toast,logout,requireAuth,initShell,wireAuth,dashboard,listCustomers,customerDetail,listProducts,productDetail,listInvoices,invoiceDetail,listPayments,listExpenses,listPurchases,listSuppliers,reports,settings,integrations,toolInit,saveProfile,submitCustomer,submitProduct,submitExpense,submitPayment,createPaymentLink,openPrint};
