const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const token=()=>localStorage.getItem('bizkit_token')||''; const user=()=>JSON.parse(localStorage.getItem('bizkit_user')||'null');
const money=v=>'₹'+Math.round(Number(v)||0).toLocaleString('en-IN');
function headers(){return {'Content-Type':'application/json',...(token()?{'Authorization':'Bearer '+token()}:{})}}
async function api(url,opt={}){try{const r=await fetch(url,{...opt,headers:{...headers(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}catch(err){if(err?.message==='Failed to fetch')toast('Network error. Please check your connection.');else toast(err.message||'Something went wrong');throw err}}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function logout(){localStorage.removeItem('bizkit_token');localStorage.removeItem('bizkit_user');location.href='/login'}
function requireAuth(){if(!token()){location.href='/login?next='+encodeURIComponent(location.pathname);return false}return true}
function setUser(){const u=user();$$('[data-user-name]').forEach(x=>x.textContent=u?.name||'');$$('[data-business]').forEach(x=>x.textContent=u?.name||'Your business')}
function activeNav(){const p=location.pathname;$$('.side a[data-route]').forEach(a=>a.classList.toggle('active',p===a.dataset.route || (a.dataset.route!=='/app'&&p.startsWith(a.dataset.route))))}
function initShell(){setUser();activeNav();const q=$('#globalSearch');if(q){let timer;q.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const v=q.value.trim();if(v.length<2)return;const d=await api('/api/search?q='+encodeURIComponent(v));const box=$('#searchResults');if(!box)return;const all=[...d.customers.map(x=>({t:'Customer',n:x.name,u:'/app/customers?id='+x.id})),...d.products.map(x=>({t:'Product',n:x.name,u:'/app/products?id='+x.id})),...d.invoices.map(x=>({t:'Invoice',n:x.invoice_no,u:'/app/invoices?id='+x.id}))];box.innerHTML=all.length?all.map(x=>`<a href="${x.u}"><b>${escapeHtml(x.t)}</b> · ${escapeHtml(x.n)}</a>`).join(''):'<div style="padding:12px;color:var(--muted)">No results</div>';box.classList.add('show')},250)});document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#searchResults')?.classList.remove('show')})}}
function wireAuth(){const form=$('#authForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const mode=form.dataset.mode;try{const body={email:$('#email').value,password:$('#password').value};if(mode==='signup')body.name=$('#name').value;const d=await api('/api/auth/'+mode,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('bizkit_token',d.token);localStorage.setItem('bizkit_user',JSON.stringify(d.user));location.href=new URLSearchParams(location.search).get('next')||'/app'}catch(err){$('#formError').textContent=err.message;$('#formError').hidden=false}})}
async function dashboard(){if(!requireAuth())return;const d=await api('/api/dashboard');$('#rev').textContent=money(d.revenue);$('#outstanding').textContent=money(d.outstanding);$('#expenses').textContent=money(d.totalExpenses);$('#profit').textContent=money(d.profitEstimate);$('#customers').textContent=d.customers;$('#lowStock').textContent=d.lowStock;const acts=$('#activity');acts.innerHTML=d.recent?.length?d.recent.map(a=>`<div class="activityItem"><span class="dot"></span><div><strong>${escapeHtml(a.title)}</strong><small>${new Date(a.created_at).toLocaleString()}</small></div></div>`).join(''):'<div class="empty">No activity yet.</div>';loadSummaryChart()}
async function loadSummaryChart(){const d=await api('/api/reports/summary');const box=$('#salesChart');if(!box)return;const max=Math.max(1,...d.months.map(x=>Number(x.sales)));box.innerHTML=d.months.map(x=>`<div class="barWrap"><div class="bar" style="height:${Math.max(4,Number(x.sales)/max*180)}px"></div><div class="barLabel">${x.month.slice(5)}</div></div>`).join('')}
async function listCustomers(){if(!requireAuth())return;const d=await api('/api/customers');$('#customerRows').innerHTML=d.customers.length?d.customers.map(c=>`<tr><td><a href="/app/customers?id=${c.id}"><b>${escapeHtml(c.name)}</b></a></td><td>${escapeHtml(c.phone||'-')}</td><td>${escapeHtml(c.email||'-')}</td><td>${escapeHtml(c.gstin||'-')}</td><td><button class="btn sm danger" onclick="editCustomer(${c.id})">Edit</button> <button class="btn sm danger" onclick="deleteCustomer(${c.id})">Delete</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No customers yet.</div></td></tr>'}
async function deleteCustomer(id){if(confirm('Delete this customer?')){await api('/api/customers/'+id,{method:'DELETE'});toast('Customer deleted');listCustomers()}}
async function customerDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/customers/'+id);$('#customerName').textContent=d.customer.name;$('#customerPhone').textContent=d.customer.phone||'-';$('#customerEmail').textContent=d.customer.email||'-';$('#customerAddress').textContent=d.customer.address||'-';$('#customerGstin').textContent=d.customer.gstin||'-';const total=d.invoices.reduce((a,x)=>a+Number(x.total||0),0),paid=d.payments.reduce((a,x)=>a+Number(x.amount||0),0);$('#customerOutstanding').textContent=money(Math.max(0,total-paid));$('#customerInvoices').innerHTML=d.invoices.length?d.invoices.map(x=>`<tr><td><a href="/app/invoices?id=${x.id}"><b>${x.invoice_no}</b></a></td><td>${x.invoice_date||'-'}</td><td>${money(x.total)}</td><td><span class="pill ${x.status==='paid'?'':'amber'}">${x.status}</span></td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No invoices.</div></td></tr>';$('#customerPayments').innerHTML=d.payments.length?d.payments.map(x=>`<tr><td>${x.paid_at||'-'}</td><td>${money(x.amount)}</td><td>${escapeHtml(x.method)}</td><td>${escapeHtml(x.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No payments.</div></td></tr>'}
async function listProducts(){if(!requireAuth())return;const d=await api('/api/products');$('#productRows').innerHTML=d.products.length?d.products.map(p=>`<tr><td><a href="/app/products?id=${p.id}"><b>${escapeHtml(p.name)}</b></a></td><td>${escapeHtml(p.sku||'-')}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.gst_rate}%</td><td>${p.stock<=p.low_stock_threshold?'<span class="pill red">Low</span>':'<span class="pill">OK</span>'}</td><td><button class="btn sm" onclick="editProduct(${p.id})">Edit</button> <button class="btn sm" onclick="adjustStock(${p.id},'in')">+ Stock</button> <button class="btn sm" onclick="adjustStock(${p.id},'out')">- Stock</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty">No products yet.</div></td></tr>'}
async function adjustStock(id,type){const q=prompt(`Quantity to ${type==='in'?'add':'remove'}:`);if(!q)return;await api('/api/products/'+id+'/adjust-stock',{method:'POST',body:JSON.stringify({quantity:Number(q),type,note:'Manual adjustment'})});toast('Stock updated');listProducts()}
async function productDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/products/'+id);$('#productName').textContent=d.product.name;$('#productSku').textContent=d.product.sku||'-';$('#productStock').textContent=d.product.stock;$('#productPrice').textContent=money(d.product.price);$('#productGst').textContent=d.product.gst_rate+'%';$('#movements').innerHTML=d.movements.length?d.movements.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString()}</td><td>${m.quantity}</td><td>${escapeHtml(m.type)}</td><td>${escapeHtml(m.note||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No stock movements.</div></td></tr>'}
async function listInvoices(){if(!requireAuth())return;const d=await api('/api/invoices');$('#invoiceRows').innerHTML=d.invoices.length?d.invoices.map(x=>`<tr><td><a href="/app/invoices?id=${x.id}"><b>${escapeHtml(x.invoice_no)}</b></a></td><td>${escapeHtml(x.customer_name||'-')}</td><td>${x.invoice_date||'-'}</td><td>${money(x.total)}</td><td><span class="pill ${x.status==='paid'?'':'amber'}">${x.status}</span></td><td><button class="btn sm" onclick="markInvoicePaid(${x.id})">Mark paid</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No invoices yet.</div></td></tr>'}
async function markInvoicePaid(id){if(!confirm('Record the remaining invoice balance as paid?'))return;const d=await api('/api/invoices/'+id);const i=d.invoice||{};const paid=(d.payments||[]).reduce((sum,p)=>sum+Number(p.amount||0),0);const balance=Math.max(0,Number(i.total||0)-paid);if(balance<=0){toast('Invoice is already fully paid');return}await api('/api/payments',{method:'POST',body:JSON.stringify({invoiceId:id,amount:balance,method:'Other',reference:'Marked paid',paidAt:new Date().toISOString().slice(0,10),note:'Balance recorded from invoice list'})});toast('Invoice balance recorded');listInvoices()}
async function invoiceDetail(){if(!requireAuth())return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const d=await api('/api/invoices/'+id);const i=d.invoice;$('#invoiceTitle').textContent=i.invoice_no;$('#invoiceCustomer').textContent=i.customer_name||'-';$('#invoiceDate').textContent=i.invoice_date||'-';$('#invoiceDue').textContent=i.due_date||'-';$('#invoiceTotal').textContent=money(i.total);$('#invoiceStatus').textContent=i.status;$('#invoiceTotalBottom').textContent=money(i.total);$('#invoiceItems').innerHTML=(i.items||[]).map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${x.qty}</td><td>${money(x.rate)}</td><td>${money(x.amount)}</td></tr>`).join('');$('#paymentRows').innerHTML=d.payments.length?d.payments.map(p=>`<tr><td>${p.paid_at||'-'}</td><td>${money(p.amount)}</td><td>${escapeHtml(p.method)}</td><td>${escapeHtml(p.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No payments recorded.</div></td></tr>';window.currentInvoice=d}
async function listPayments(){if(!requireAuth())return;const d=await api('/api/payments');const total=(d.payments||[]).reduce((sum,p)=>sum+Number(p.amount||0),0);if($('#paymentTotal'))$('#paymentTotal').textContent=money(total);if($('#paymentCount'))$('#paymentCount').textContent=String((d.payments||[]).length);const [inv,customers]=await Promise.all([api('/api/invoices'),api('/api/customers')]);const invoiceSelect=$('#pay_invoice'),customerSelect=$('#pay_customer');if(invoiceSelect)invoiceSelect.innerHTML='<option value="">Select invoice</option>'+(inv.invoices||[]).filter(x=>x.status!=='paid'&&x.status!=='cancelled').map(x=>'<option value="'+x.id+'">'+escapeHtml(x.invoice_no)+' · '+money(x.total)+' · '+escapeHtml(x.customer_name||'')+'</option>').join('');if(customerSelect)customerSelect.innerHTML='<option value="">Select customer</option>'+(customers.customers||[]).map(x=>'<option value="'+x.id+'">'+escapeHtml(x.name)+'</option>').join('');if(invoiceSelect&&!invoiceSelect.dataset.bound){invoiceSelect.dataset.bound='1';invoiceSelect.addEventListener('change',()=>{const chosen=(inv.invoices||[]).find(x=>String(x.id)===String(invoiceSelect.value));if(chosen?.customer_id&&customerSelect)customerSelect.value=String(chosen.customer_id)})}$('#paymentRowsMain').innerHTML=d.payments.length?d.payments.map(p=>`<tr><td>${p.paid_at||'-'}</td><td>${escapeHtml(p.customer_name||'-')}</td><td>${escapeHtml(p.invoice_no||'-')}</td><td>${money(p.amount)}</td><td>${escapeHtml(p.method)}</td><td>${escapeHtml(p.reference||'-')}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No payments yet.</div></td></tr>'}
async function listExpenses(){if(!requireAuth())return;const d=await api('/api/expenses');$('#expenseRows').innerHTML=d.expenses.length?d.expenses.map(x=>`<tr><td>${x.expense_date||'-'}</td><td>${escapeHtml(x.category)}</td><td>${money(x.amount)}</td><td>${escapeHtml(x.note||'-')}</td><td><button class="btn sm" onclick="editExpense(${x.id})">Edit</button> <button class="btn sm danger" onclick="deleteExpense(${x.id})">Delete</button></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No expenses yet.</div></td></tr>'}
function resetExpenseModal(){const modal=$('#expenseModal');if(!modal)return;delete modal.dataset.editId;const title=modal.querySelector('h3');if(title)title.textContent='New expense';const btn=modal.querySelector('.btn.primary');if(btn)btn.textContent='Save expense';}
async function editExpense(id){const d=await api('/api/expenses');const x=(d.expenses||[]).find(v=>String(v.id)===String(id));if(!x)return;$('#e_date').value=x.expense_date||'';$('#e_cat').value=x.category||'Other';$('#e_amount').value=x.amount||0;$('#e_note').value=x.note||'';const modal=$('#expenseModal');modal.dataset.editId=String(id);const title=modal.querySelector('h3');if(title)title.textContent='Edit expense';const btn=modal.querySelector('.btn.primary');if(btn)btn.textContent='Save changes';modal.classList.add('show')}
async function deleteExpense(id){if(confirm('Delete expense?')){await api('/api/expenses/'+id,{method:'DELETE'});toast('Expense deleted');listExpenses()}}
async function listPurchases(){if(!requireAuth())return;const d=await api('/api/purchases');$('#purchaseRows').innerHTML=d.purchases.length?d.purchases.map(x=>`<tr><td>${escapeHtml(x.purchase_no)}</td><td>${escapeHtml(x.supplier_name||'-')}</td><td>${x.purchase_date||'-'}</td><td>${money(x.total)}</td><td>${escapeHtml(x.status)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No purchases yet.</div></td></tr>'}
async function listSuppliers(){if(!requireAuth())return;const d=await api('/api/suppliers');$('#supplierRows').innerHTML=d.suppliers.length?d.suppliers.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.phone||'-')}</td><td>${escapeHtml(x.email||'-')}</td><td>${escapeHtml(x.gstin||'-')}</td></tr>`).join(''):'<tr><td colspan="4"><div class="empty">No suppliers yet.</div></td></tr>'}
async function reports(){if(!requireAuth())return;const d=await api('/api/reports/summary');const totals=d.months.reduce((a,x)=>{a.s+=Number(x.sales);a.e+=Number(x.expenses);return a},{s:0,e:0});$('#repSales').textContent=money(totals.s);$('#repExpenses').textContent=money(totals.e);$('#repProfit').textContent=money(totals.s-totals.e);const max=Math.max(1,...d.months.map(x=>Number(x.sales)));$('#reportChart').innerHTML=d.months.map(x=>`<div class="barWrap"><div class="bar" style="height:${Math.max(5,Number(x.sales)/max*180)}px"></div><div class="barLabel">${x.month}</div></div>`).join('')}
async function settings(){if(!requireAuth())return;const d=await api('/api/profile');const p=d.profile||{};for(const [id,val] of Object.entries({businessName:p.businessName||'',businessType:p.businessType||'Services',phone:p.phone||'',email:p.email||'',gstin:p.gstin||'',state:p.state||'',address:p.address||'',currency:p.currency||'INR'})){const el=$('#set_'+id);if(el)el.value=val}const s=await api('/api/integrations/status');$('#rzStatus').textContent=s.razorpay?'Configured':'Not configured';$('#waStatus').textContent=s.whatsapp?'Configured':'Not configured';$('#mailStatus').textContent=s.email?'Configured':'Not configured'}
function toolInit(){if(!requireAuth())return;const forms={gst:['gstMode','gstAmount','gstRate'],profit:['cost','sell'],break:['fixed','price','variable'],salary:['ctc','bonus','pf','other']};function calc(id){if(id==='gst'){const a=n($('#gstAmount').value),r=n($('#gstRate').value);if($('#gstMode').value==='add'){const tax=a*r/100;$('#gstRes').textContent=`Base ${money(a)} · GST ${money(tax)} · Total ${money(a+tax)}`}else{const base=a/(1+r/100),tax=a-base;$('#gstRes').textContent=`Base ${money(base)} · GST ${money(tax)} · Total ${money(a)}`}}if(id==='profit'){const c=n($('#cost').value),s=n($('#sell').value),p=s-c;$('#profitRes').textContent=`Profit ${money(p)} · Margin ${(s?p/s*100:0).toFixed(1)}% · Markup ${(c?p/c*100:0).toFixed(1)}%`}if(id==='break'){const f=n($('#fixed').value),p=n($('#price').value),v=n($('#variable').value),m=p-v;$('#breakRes').textContent=m>0?`Break-even ${Math.ceil(f/m)} units · Sales ${money(Math.ceil(f/m)*p)}`:'Selling price must exceed variable cost'}if(id==='salary'){const c=n($('#ctc').value),b=n($('#bonus').value),pf=n($('#pf').value),o=n($('#other').value),g=(c-b)/12;$('#salaryRes').textContent=`Monthly gross ${money(g)} · Estimated take-home ${money(Math.max(0,g-pf-o))}`}}$$('[data-calc]').forEach(b=>b.onclick=()=>calc(b.dataset.calc))}
async function integrations(){if(!requireAuth())return;const d=await api('/api/integrations/status');$('#rzStatus').textContent=d.razorpay?'Connected':'Not configured';$('#waStatus').textContent=d.whatsapp?'Connected':'Not configured';$('#mailStatus').textContent=d.email?'Connected':'Not configured'}
async function saveProfile(){const b={businessName:$('#set_businessName').value,businessType:$('#set_businessType').value,phone:$('#set_phone').value,email:$('#set_email').value,gstin:$('#set_gstin').value,state:$('#set_state').value,address:$('#set_address').value,currency:$('#set_currency').value};await api('/api/profile',{method:'PUT',body:JSON.stringify(b)});toast('Business profile saved')}
async function editCustomer(id){const d=await api('/api/customers/'+id);const c=d.customer;for(const [id2,val] of Object.entries({name:c.name||'',phone:c.phone||'',email:c.email||'',gstin:c.gstin||'',address:c.address||'',notes:c.notes||''})){const el=$('#c_'+id2);if(el)el.value=val}const modal=$('#customerModal');modal.dataset.editId=String(id);$('#customerModalTitle').textContent='Edit customer';$('#customerSaveBtn').textContent='Save changes';modal.classList.add('show')}
function resetCustomerModal(){const modal=$('#customerModal');if(!modal)return;delete modal.dataset.editId;$('#customerModalTitle').textContent='New customer';$('#customerSaveBtn').textContent='Save customer';['c_name','c_phone','c_email','c_gstin','c_address','c_notes'].forEach(id=>{const el=$('#'+id);if(el)el.value=''})}
async function submitCustomer(){const b={name:$('#c_name').value.trim(),phone:$('#c_phone').value.trim(),email:$('#c_email').value.trim(),address:$('#c_address').value.trim(),gstin:$('#c_gstin').value.trim(),notes:$('#c_notes').value.trim()},modal=$('#customerModal'),editId=modal?.dataset.editId;if(!b.name){toast('Customer name is required');return}if(editId)await api('/api/customers/'+editId,{method:'PUT',body:JSON.stringify(b)});else await api('/api/customers',{method:'POST',body:JSON.stringify(b)});toast(editId?'Customer updated':'Customer created');location.href='/app/customers'}
async function editProduct(id){const d=await api('/api/products/'+id);const p=d.product;for(const [id2,val] of Object.entries({name:p.name||'',sku:p.sku||'',hsn:p.hsn_sac||'',unit:p.unit||'pcs',price:p.price||0,purchase:p.purchase_price||0,gst:p.gst_rate??18,stock:p.stock||0,low:p.low_stock_threshold??5})){const el=$('#p_'+id2);if(el)el.value=val}if($('#p_track'))$('#p_track').checked=p.track_stock!==false;const modal=$('#productModal');modal.dataset.editId=String(id);$('#productModalTitle').textContent='Edit product';$('#productSaveBtn').textContent='Save changes';modal.classList.add('show')}
function resetProductModal(){const modal=$('#productModal');if(!modal)return;delete modal.dataset.editId;$('#productModalTitle').textContent='New product';$('#productSaveBtn').textContent='Save product'}
async function submitProduct(){const b={name:$('#p_name').value.trim(),sku:$('#p_sku').value.trim(),hsnSac:$('#p_hsn').value.trim(),unit:$('#p_unit').value,price:n($('#p_price').value),purchasePrice:n($('#p_purchase').value),gstRate:n($('#p_gst').value),stock:n($('#p_stock').value),lowStockThreshold:n($('#p_low').value),trackStock:$('#p_track').checked},modal=$('#productModal'),editId=modal?.dataset.editId;if(!b.name){toast('Product name is required');return}if(b.price<0||b.purchasePrice<0||b.stock<0||b.lowStockThreshold<0||b.gstRate<0||b.gstRate>100){toast('Check product values');return}if(editId)await api('/api/products/'+editId,{method:'PUT',body:JSON.stringify(b)});else await api('/api/products',{method:'POST',body:JSON.stringify(b)});toast(editId?'Product updated':'Product added');location.href='/app/products'}
async function submitExpense(){const modal=$('#expenseModal'),editId=modal?.dataset.editId,amount=n($('#e_amount').value);if(amount<=0){toast('Enter an expense amount greater than zero');return}const payload={expenseDate:$('#e_date').value,category:$('#e_cat').value,amount,note:$('#e_note').value.trim()};if(editId)await api('/api/expenses/'+editId,{method:'PUT',body:JSON.stringify(payload)});else await api('/api/expenses',{method:'POST',body:JSON.stringify(payload)});toast(editId?'Expense updated':'Expense added');location.href='/app/expenses'}
async function submitPayment(){await api('/api/payments',{method:'POST',body:JSON.stringify({invoiceId:$('#pay_invoice').value||null,customerId:$('#pay_customer').value||null,amount:n($('#pay_amount').value),method:$('#pay_method').value,reference:$('#pay_ref').value,paidAt:$('#pay_date').value,note:$('#pay_note').value})});toast('Payment recorded');location.href='/app/payments'}
async function createPaymentLink(){const d=await api('/api/integrations/razorpay/payment-link',{method:'POST',body:JSON.stringify({amount:n($('#pl_amount').value),customerName:$('#pl_name').value,customerPhone:$('#pl_phone').value,customerEmail:$('#pl_email').value,referenceId:$('#pl_ref').value,description:$('#pl_desc').value})});$('#linkResult').innerHTML=`<div class="success">Payment link created: <a href="${d.short_url}" target="_blank"><b>${d.short_url}</b></a></div>`}
function openPrint(){window.print()}
window.Biz={api,toast,convertQuotationToInvoice,deleteInvoice,editCustomer,editProduct,editExpense,resetExpenseModal,editCustomer,resetCustomerModal,editProduct,resetProductModal,logout,requireAuth,initShell,wireAuth,dashboard,listCustomers,customerDetail,listProducts,productDetail,listInvoices,invoiceDetail,listPayments,listExpenses,listPurchases,listSuppliers,reports,settings,integrations,toolInit,saveProfile,submitCustomer,submitProduct,submitExpense,submitPayment,createPaymentLink,openPrint};

/* Phase 3 workflow UX */
function installWorkflowUx(){
  const wrap=(name,check)=>{
    if(!window.Biz?.[name]||window.Biz['__wrapped_'+name])return;
    const original=window.Biz[name];
    window.Biz['__wrapped_'+name]=true;
    window.Biz[name]=async function(){if(!check())return;return original.apply(this,arguments)}
  };
  wrap('submitCustomer',()=>{const n=$('#c_name')?.value.trim();if(!n){toast('Customer name is required');$('#c_name')?.focus();return false}return true});
  wrap('submitProduct',()=>{const name=$('#p_name')?.value.trim(),price=Number($('#p_price')?.value)||0,gst=Number($('#p_gst')?.value)||0;if(!name){toast('Product name is required');$('#p_name')?.focus();return false}if(price<0||gst<0||gst>100){toast('Check product price and GST rate');return false}return true});
  wrap('submitExpense',()=>{const amount=n($('#e_amount')?.value);if(amount<=0){toast('Enter an expense amount greater than zero');$('#e_amount')?.focus();return false}return true});
  wrap('submitPayment',()=>{const amount=n($('#pay_amount')?.value),invoice=$('#pay_invoice')?.value.trim(),customer=$('#pay_customer')?.value.trim();if(amount<=0){toast('Enter a payment amount greater than zero');$('#pay_amount')?.focus();return false}if(!invoice&&!customer){toast('Add an invoice ID or customer ID');return false}return true});
  const wrapGlobal=(name,check)=>{
    if(typeof window[name]!=='function'||window['__wrapped_'+name])return;
    const original=window[name];window['__wrapped_'+name]=true;
    window[name]=function(){if(!check())return;return original.apply(this,arguments)}
  };
  wrapGlobal('saveNewInvoice',()=>{const no=$('#inv_no')?.value.trim(),customer=$('#inv_customer')?.value.trim();if(!no||!customer){toast('Invoice number and customer name are required');return false}if(!invItems?.length){toast('Add at least one item');return false}return true});
  wrapGlobal('saveNewQuote',()=>{if(!$('#q_no')?.value.trim()||!$('#q_customer')?.value.trim()){toast('Quotation number and customer name are required');return false}if(!quoteItems?.length){toast('Add at least one item');return false}return true});
  wrapGlobal('savePurchase',()=>{if(!$('#pu_no')?.value.trim()||!$('#pu_supplier')?.value.trim()){toast('Purchase number and supplier are required');return false}if(!purchaseItems?.length){toast('Add at least one item');return false}return true});
  const bind=()=>{
    const inv=()=>{updateInvoiceSummary()};
    ['inv_discount','inv_gst','inv_amount'].forEach(id=>$('#'+id)?.addEventListener('input',inv));
    $('#inv_item')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addInvItem()}});
    $('#q_item')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addQuoteItem()}});
    $('#pu_item')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addPurchaseItem()}});
  };
  bind();
}
setTimeout(installWorkflowUx,0);

function updateInvoiceSummary(){const subtotal=(typeof invItems!=='undefined'?invItems:[]).reduce((a,x)=>a+Number(x.qty||1)*Number(x.rate||0),0),discount=Math.max(0,Number($('#inv_discount')?.value)||0),gstRate=Math.max(0,Number($('#inv_gst')?.value)||0),taxable=Math.max(0,subtotal-discount),gst=taxable*gstRate/100,total=taxable+gst;const count=$('#invItemCount'),sub=$('#invSubtotal'),tax=$('#invTax'),tot=$('.summaryTotal strong');if(count)count.textContent=String((typeof invItems!=='undefined'?invItems:[]).length);if(sub)sub.textContent=money(subtotal);if(tax)tax.textContent=money(gst);if(tot)tot.textContent=money(total)}
function installCoreWorkflowEnhancements(){
  const setTotal=(id,items)=>{const total=(items||[]).reduce((sum,x)=>sum+Number(x.qty||1)*Number(x.rate||0),0);const el=$('#'+id);if(el)el.textContent=money(total)};
  const wrapGlobal=(name,after)=>{
    if(typeof window[name]!=='function'||window['__enh_'+name])return;
    const original=window[name];window['__enh_'+name]=true;
    window[name]=function(){const result=original.apply(this,arguments);setTimeout(after,0);return result}
  };
  wrapGlobal('addInvItem',()=>updateInvoiceSummary());
  wrapGlobal('renderInvItems',()=>updateInvoiceSummary());
  wrapGlobal('addQuoteItem',()=>setTotal('qSubtotal',typeof quoteItems!=='undefined'?quoteItems:[]));
  wrapGlobal('addPurchaseItem',()=>setTotal('puSubtotal',typeof purchaseItems!=='undefined'?purchaseItems:[]));
  wrapGlobal('renderQuoteItems',()=>setTotal('qSubtotal',typeof quoteItems!=='undefined'?quoteItems:[]));
  wrapGlobal('renderPurchaseItems',()=>setTotal('puSubtotal',typeof purchaseItems!=='undefined'?purchaseItems:[]));
  if(typeof window.adjustStock==='function'&&!window.__enh_adjustStock){
    const original=window.adjustStock;window.__enh_adjustStock=true;
    window.adjustStock=async function(id,type){const q=prompt('Quantity to '+(type==='in'?'add':'remove')+':');const qty=Number(q);if(!Number.isFinite(qty)||qty<=0){toast('Enter a quantity greater than zero');return}return api('/api/products/'+id+'/adjust-stock',{method:'POST',body:JSON.stringify({quantity:qty,type,note:'Manual adjustment'})}).then(()=>{toast('Stock updated');return listProducts()}).catch(()=>{})}
  }
}
setTimeout(installCoreWorkflowEnhancements,0);

async function convertQuotationToInvoice(id){if(!confirm('Convert this quotation into an invoice?'))return;try{const d=await api('/api/quotations/'+id+'/convert-to-invoice',{method:'POST'});toast('Invoice created from quotation');location.href='/app/invoices?id='+d.id}catch(e){}}

async function deleteInvoice(id){if(!id||!confirm('Delete this invoice? Paid invoices cannot be deleted.'))return;try{await api('/api/invoices/'+id,{method:'DELETE'});toast('Invoice deleted');location.href='/app/invoices'}catch(e){}}
