const express=require('express');
const path=require('path');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const {Pool}=require('pg');
const app=express();
app.disable('x-powered-by');
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET;
const DATABASE_URL=process.env.DATABASE_URL;
if(!JWT_SECRET||JWT_SECRET.length<32) throw new Error('JWT_SECRET must be set and at least 32 characters');
if(!DATABASE_URL) throw new Error('DATABASE_URL must be set');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false},max:5,family:4,connectionTimeoutMillis:10000,keepAlive:true});
const q=(text,params=[])=>pool.query(text,params), rows=r=>r.rows, row=r=>r.rows[0];
const n=v=>Number(v)||0;
const moneyInt=v=>Math.round(n(v)*100);
function dateISO(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function normalizeEmail(v){return String(v||'').trim().toLowerCase()}
function tokenFor(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:'7d'})}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired session'})}}
function calcDoc(b){const items=Array.isArray(b.items)?b.items.map(x=>({productId:x.productId||null,name:String(x.name||'Item'),qty:n(x.qty),rate:n(x.rate),gstRate:n(x.gstRate??b.gstRate),amount:n(x.qty)*n(x.rate)})):[];const subtotal=items.reduce((a,x)=>a+x.amount,0);const discount=Math.max(0,n(b.discount));const gstRate=Math.max(0,n(b.gstRate));const taxable=Math.max(0,subtotal-discount);const gstAmount=taxable*gstRate/100;return{items,subtotal,discount,gstRate,gstAmount,total:taxable+gstAmount}}
async function initDb(){await q(`
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS business_profiles(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,business_name TEXT,business_type TEXT,phone TEXT,email TEXT,gstin TEXT,address TEXT,state TEXT,logo_url TEXT,currency TEXT DEFAULT 'INR');
CREATE TABLE IF NOT EXISTS customers(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,gstin TEXT,notes TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS suppliers(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,gstin TEXT,notes TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS products(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,sku TEXT,hsn_sac TEXT,unit TEXT DEFAULT 'pcs',price DOUBLE PRECISION NOT NULL DEFAULT 0,purchase_price DOUBLE PRECISION NOT NULL DEFAULT 0,gst_rate DOUBLE PRECISION NOT NULL DEFAULT 18,stock DOUBLE PRECISION NOT NULL DEFAULT 0,low_stock_threshold DOUBLE PRECISION NOT NULL DEFAULT 5,track_stock BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS invoices(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,invoice_no TEXT NOT NULL,invoice_date DATE,due_date DATE,customer_id BIGINT,customer_name TEXT,customer_phone TEXT,customer_address TEXT,gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,discount DOUBLE PRECISION NOT NULL DEFAULT 0,items_json JSONB NOT NULL DEFAULT '[]',subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,gst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,total DOUBLE PRECISION NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'unpaid',notes TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS quotations(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,quote_no TEXT NOT NULL,quote_date DATE,valid_until DATE,customer_id BIGINT,customer_name TEXT,customer_phone TEXT,customer_address TEXT,gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,discount DOUBLE PRECISION NOT NULL DEFAULT 0,items_json JSONB NOT NULL DEFAULT '[]',subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,gst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,total DOUBLE PRECISION NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',notes TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS payments(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,invoice_id BIGINT,customer_id BIGINT,amount DOUBLE PRECISION NOT NULL,method TEXT NOT NULL DEFAULT 'cash',reference TEXT,paid_at DATE DEFAULT CURRENT_DATE,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS expenses(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expense_date DATE,category TEXT NOT NULL,amount DOUBLE PRECISION NOT NULL DEFAULT 0,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stock_movements(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,product_id BIGINT,quantity DOUBLE PRECISION NOT NULL,type TEXT NOT NULL,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS purchases(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,purchase_no TEXT NOT NULL,purchase_date DATE,supplier_id BIGINT,supplier_name TEXT,items_json JSONB NOT NULL DEFAULT '[]',subtotal DOUBLE PRECISION DEFAULT 0,gst_amount DOUBLE PRECISION DEFAULT 0,total DOUBLE PRECISION DEFAULT 0,status TEXT DEFAULT 'received',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS activity(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,title TEXT NOT NULL,meta JSONB DEFAULT '{}',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS integration_settings(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,razorpay_enabled BOOLEAN DEFAULT FALSE,whatsapp_enabled BOOLEAN DEFAULT FALSE,email_enabled BOOLEAN DEFAULT FALSE,updated_at TIMESTAMPTZ DEFAULT NOW());
`)}
async function logActivity(userId,type,title,meta={}){try{await q('INSERT INTO activity(user_id,type,title,meta) VALUES($1,$2,$3,$4)',[userId,type,title,JSON.stringify(meta)])}catch{}}

app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');next()});
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));

// Auth
app.post('/api/auth/signup',async(req,res)=>{try{const{name,email,password}=req.body||{};if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});if(password.length<6)return res.status(400).json({error:'Password must contain at least 6 characters'});const em=normalizeEmail(email),hash=await bcrypt.hash(password,12),u=row(await q('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email',[String(name).trim(),em,hash]));await q('INSERT INTO business_profiles(user_id,business_name,email) VALUES($1,$2,$3)',[u.id,String(name).trim(),em]);await q('INSERT INTO integration_settings(user_id) VALUES($1) ON CONFLICT DO NOTHING',[u.id]);res.status(201).json({user:u,token:tokenFor(u)})}catch(e){if(e.code==='23505')return res.status(409).json({error:'An account with this email already exists'});console.error(e);res.status(500).json({error:'Could not create account'})}});
app.post('/api/auth/login',async(req,res)=>{try{const em=normalizeEmail(req.body?.email),password=req.body?.password||'',u=row(await q('SELECT * FROM users WHERE email=$1',[em]));if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Email or password is incorrect'});res.json({user:{id:Number(u.id),name:u.name,email:u.email},token:tokenFor(u)})}catch{res.status(500).json({error:'Could not log in'})}});
app.get('/api/me',auth,async(req,res)=>res.json({user:row(await q('SELECT id,name,email,created_at FROM users WHERE id=$1',[req.user.id]))}));

// Profile & integrations
app.get('/api/profile',auth,async(req,res)=>res.json({profile:row(await q('SELECT business_name AS "businessName",business_type AS "businessType",phone,email,gstin,address,state,logo_url AS "logoUrl",currency FROM business_profiles WHERE user_id=$1',[req.user.id]))||{}}));
app.put('/api/profile',auth,async(req,res)=>{const p=req.body||{};await q(`INSERT INTO business_profiles(user_id,business_name,business_type,phone,email,gstin,address,state,logo_url,currency) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(user_id) DO UPDATE SET business_name=EXCLUDED.business_name,business_type=EXCLUDED.business_type,phone=EXCLUDED.phone,email=EXCLUDED.email,gstin=EXCLUDED.gstin,address=EXCLUDED.address,state=EXCLUDED.state,logo_url=EXCLUDED.logo_url,currency=EXCLUDED.currency`,[req.user.id,p.businessName||'',p.businessType||'',p.phone||'',p.email||'',p.gstin||'',p.address||'',p.state||'',p.logoUrl||'',p.currency||'INR']);await logActivity(req.user.id,'settings','Business profile updated');res.json({ok:true})});
app.get('/api/integrations',auth,async(req,res)=>{const s=row(await q('SELECT * FROM integration_settings WHERE user_id=$1',[req.user.id]))||{};res.json({configured:{razorpay:Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),whatsapp:Boolean(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID),email:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER)}})});

// Customers
app.get('/api/customers',auth,async(req,res)=>res.json({customers:rows(await q('SELECT * FROM customers WHERE user_id=$1 ORDER BY id DESC',[req.user.id]))}));
app.get('/api/customers/:id',auth,async(req,res)=>{const customer=row(await q('SELECT * FROM customers WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]));if(!customer)return res.status(404).json({error:'Customer not found'});const invoices=rows(await q('SELECT id,invoice_no,invoice_date,total,status FROM invoices WHERE customer_id=$1 AND user_id=$2 ORDER BY id DESC',[req.params.id,req.user.id]));const payments=rows(await q('SELECT id,amount,method,reference,paid_at FROM payments WHERE customer_id=$1 AND user_id=$2 ORDER BY id DESC',[req.params.id,req.user.id]));res.json({customer,invoices,payments})});
app.post('/api/customers',auth,async(req,res)=>{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Customer name is required'});const i=row(await q('INSERT INTO customers(user_id,name,phone,email,address,gstin,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.user.id,b.name,b.phone||'',b.email||'',b.address||'',b.gstin||'',b.notes||'']));await logActivity(req.user.id,'customer','Customer created',{id:i.id,name:b.name});res.status(201).json({id:Number(i.id)})});
app.put('/api/customers/:id',auth,async(req,res)=>{const b=req.body||{},r=await q('UPDATE customers SET name=$1,phone=$2,email=$3,address=$4,gstin=$5,notes=$6 WHERE id=$7 AND user_id=$8',[b.name,b.phone||'',b.email||'',b.address||'',b.gstin||'',b.notes||'',req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Customer not found'});res.json({ok:true})});
app.delete('/api/customers/:id',auth,async(req,res)=>{await q('DELETE FROM customers WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Suppliers
app.get('/api/suppliers',auth,async(req,res)=>res.json({suppliers:rows(await q('SELECT * FROM suppliers WHERE user_id=$1 ORDER BY id DESC',[req.user.id]))}));
app.post('/api/suppliers',auth,async(req,res)=>{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Supplier name is required'});const i=row(await q('INSERT INTO suppliers(user_id,name,phone,email,address,gstin,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.user.id,b.name,b.phone||'',b.email||'',b.address||'',b.gstin||'',b.notes||'']));res.status(201).json({id:Number(i.id)})});

// Products/inventory
app.get('/api/products',auth,async(req,res)=>res.json({products:rows(await q('SELECT * FROM products WHERE user_id=$1 ORDER BY id DESC',[req.user.id]))}));
app.get('/api/products/:id',auth,async(req,res)=>{const p=row(await q('SELECT * FROM products WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]));if(!p)return res.status(404).json({error:'Product not found'});const movements=rows(await q('SELECT id,quantity,type,note,created_at FROM stock_movements WHERE product_id=$1 AND user_id=$2 ORDER BY id DESC LIMIT 50',[req.params.id,req.user.id]));res.json({product:p,movements})});
app.post('/api/products',auth,async(req,res)=>{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Product/service name is required'});const i=row(await q('INSERT INTO products(user_id,name,sku,hsn_sac,unit,price,purchase_price,gst_rate,stock,low_stock_threshold,track_stock) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[req.user.id,b.name,b.sku||'',b.hsnSac||'',b.unit||'pcs',n(b.price),n(b.purchasePrice),n(b.gstRate)||18,n(b.stock),n(b.lowStockThreshold)||5,b.trackStock!==false]));if(n(b.stock))await q('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,i.id,n(b.stock),'opening','Opening stock']);res.status(201).json({id:Number(i.id)})});
app.put('/api/products/:id',auth,async(req,res)=>{const b=req.body||{};const old=row(await q('SELECT stock FROM products WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]));if(!old)return res.status(404).json({error:'Product not found'});const newStock=n(b.stock);const r=await q('UPDATE products SET name=$1,sku=$2,hsn_sac=$3,unit=$4,price=$5,purchase_price=$6,gst_rate=$7,stock=$8,low_stock_threshold=$9,track_stock=$10 WHERE id=$11 AND user_id=$12',[b.name,b.sku||'',b.hsnSac||'',b.unit||'pcs',n(b.price),n(b.purchasePrice),n(b.gstRate)||18,newStock,n(b.lowStockThreshold)||5,b.trackStock!==false,req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});if(newStock!==n(old.stock))await q('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,req.params.id,newStock-n(old.stock),'adjustment','Manual stock adjustment']);res.json({ok:true})});
app.post('/api/products/:id/adjust-stock',auth,async(req,res)=>{const qty=n(req.body?.quantity);const type=req.body?.type==='out'?'out':'in';const signed=type==='out'?-Math.abs(qty):Math.abs(qty);await q('UPDATE products SET stock=stock+$1 WHERE id=$2 AND user_id=$3',[signed,req.params.id,req.user.id]);await q('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,req.params.id,signed,'adjustment',req.body?.note||'Stock adjustment']);res.json({ok:true})});
app.delete('/api/products/:id',auth,async(req,res)=>{await q('DELETE FROM products WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Invoices
app.get('/api/invoices',auth,async(req,res)=>res.json({invoices:rows(await q('SELECT * FROM invoices WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).map(r=>({...r,items:r.items_json}))}));
app.get('/api/invoices/:id',auth,async(req,res)=>{const invoice=row(await q('SELECT * FROM invoices WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]));if(!invoice)return res.status(404).json({error:'Invoice not found'});const payments=rows(await q('SELECT * FROM payments WHERE invoice_id=$1 AND user_id=$2 ORDER BY id DESC',[req.params.id,req.user.id]));res.json({invoice:{...invoice,items:invoice.items_json},payments})});
app.post('/api/invoices',auth,async(req,res)=>{const b=req.body||{},c=calcDoc(b),i=row(await q(`INSERT INTO invoices(user_id,invoice_no,invoice_date,due_date,customer_id,customer_name,customer_phone,customer_address,gst_rate,discount,items_json,subtotal,gst_amount,total,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,$15,$16) RETURNING id`,[req.user.id,b.invoiceNo||`INV-${Date.now().toString().slice(-6)}`,b.invoiceDate||dateISO(),b.dueDate||null,b.customerId||null,b.customerName||'',b.customerPhone||'',b.customerAddress||'',c.gstRate,c.discount,JSON.stringify(c.items),c.subtotal,c.gstAmount,c.total,b.status||'unpaid',b.notes||'']));for(const it of c.items)if(it.productId){await q('UPDATE products SET stock=stock-$1 WHERE id=$2 AND user_id=$3 AND track_stock=TRUE',[it.qty,it.productId,req.user.id]);await q('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,it.productId,-it.qty,'sale',b.invoiceNo||'Invoice'])}await logActivity(req.user.id,'invoice','Invoice created',{id:i.id,invoiceNo:b.invoiceNo,total:c.total});res.status(201).json({id:Number(i.id),total:c.total})});
app.put('/api/invoices/:id',auth,async(req,res)=>{const b=req.body||{},c=calcDoc(b);const r=await q(`UPDATE invoices SET invoice_no=$1,invoice_date=$2,due_date=$3,customer_id=$4,customer_name=$5,customer_phone=$6,customer_address=$7,gst_rate=$8,discount=$9,items_json=$10::jsonb,subtotal=$11,gst_amount=$12,total=$13,status=$14,notes=$15,updated_at=NOW() WHERE id=$16 AND user_id=$17`,[b.invoiceNo||'INV-001',b.invoiceDate||dateISO(),b.dueDate||null,b.customerId||null,b.customerName||'',b.customerPhone||'',b.customerAddress||'',c.gstRate,c.discount,JSON.stringify(c.items),c.subtotal,c.gstAmount,c.total,b.status||'unpaid',b.notes||'',req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Invoice not found'});res.json({ok:true})});
app.patch('/api/invoices/:id/status',auth,async(req,res)=>{const allowed=['unpaid','paid','overdue','cancelled','partial'];const status=allowed.includes(req.body?.status)?req.body.status:'unpaid';await q('UPDATE invoices SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3',[status,req.params.id,req.user.id]);res.json({ok:true})});
app.delete('/api/invoices/:id',auth,async(req,res)=>{await q('DELETE FROM invoices WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Quotations
app.get('/api/quotations',auth,async(req,res)=>res.json({quotations:rows(await q('SELECT * FROM quotations WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).map(r=>({...r,items:r.items_json}))}));
app.post('/api/quotations',auth,async(req,res)=>{const b=req.body||{},c=calcDoc(b),i=row(await q(`INSERT INTO quotations(user_id,quote_no,quote_date,valid_until,customer_id,customer_name,customer_phone,customer_address,gst_rate,discount,items_json,subtotal,gst_amount,total,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,$15,$16) RETURNING id`,[req.user.id,b.quoteNo||`QUO-${Date.now().toString().slice(-6)}`,b.quoteDate||dateISO(),b.validUntil||null,b.customerId||null,b.customerName||'',b.customerPhone||'',b.customerAddress||'',c.gstRate,c.discount,JSON.stringify(c.items),c.subtotal,c.gstAmount,c.total,b.status||'draft',b.notes||'']));res.status(201).json({id:Number(i.id),total:c.total})});
app.patch('/api/quotations/:id/status',auth,async(req,res)=>{const allowed=['draft','sent','accepted','rejected','expired'];const status=allowed.includes(req.body?.status)?req.body.status:'draft';await q('UPDATE quotations SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3',[status,req.params.id,req.user.id]);res.json({ok:true})});
app.delete('/api/quotations/:id',auth,async(req,res)=>{await q('DELETE FROM quotations WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Payments
app.get('/api/payments',auth,async(req,res)=>res.json({payments:rows(await q('SELECT p.*,i.invoice_no,c.name AS customer_name FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id LEFT JOIN customers c ON c.id=p.customer_id WHERE p.user_id=$1 ORDER BY p.id DESC',[req.user.id]))}));
app.post('/api/payments',auth,async(req,res)=>{const b=req.body||{};const amount=n(b.amount);if(amount<=0)return res.status(400).json({error:'Payment amount is required'});const i=row(await q('INSERT INTO payments(user_id,invoice_id,customer_id,amount,method,reference,paid_at,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[req.user.id,b.invoiceId||null,b.customerId||null,amount,b.method||'cash',b.reference||'',b.paidAt||dateISO(),b.note||'']));if(b.invoiceId){const inv=row(await q('SELECT total FROM invoices WHERE id=$1 AND user_id=$2',[b.invoiceId,req.user.id]));const paid=n(row(await q('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE invoice_id=$1 AND user_id=$2',[b.invoiceId,req.user.id])).total);const status=paid+0.01>=n(inv?.total)?'paid':'partial';await q('UPDATE invoices SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3',[status,b.invoiceId,req.user.id])}res.status(201).json({id:Number(i.id)})});

// Expenses
app.get('/api/expenses',auth,async(req,res)=>res.json({expenses:rows(await q('SELECT * FROM expenses WHERE user_id=$1 ORDER BY id DESC',[req.user.id]))}));
app.post('/api/expenses',auth,async(req,res)=>{const b=req.body||{};if(!b.category||n(b.amount)<=0)return res.status(400).json({error:'Category and amount are required'});const i=row(await q('INSERT INTO expenses(user_id,expense_date,category,amount,note) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.user.id,b.expenseDate||dateISO(),b.category,n(b.amount),b.note||'']));await logActivity(req.user.id,'expense','Expense added',{id:i.id,amount:n(b.amount)});res.status(201).json({id:Number(i.id)})});
app.delete('/api/expenses/:id',auth,async(req,res)=>{await q('DELETE FROM expenses WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Purchases
app.get('/api/purchases',auth,async(req,res)=>res.json({purchases:rows(await q('SELECT * FROM purchases WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).map(r=>({...r,items:r.items_json}))}));
app.post('/api/purchases',auth,async(req,res)=>{const b=req.body||{},items=Array.isArray(b.items)?b.items:[],subtotal=items.reduce((a,x)=>a+n(x.qty)*n(x.rate),0),gst=subtotal*n(b.gstRate)/100,total=subtotal+gst,i= row(await q(`INSERT INTO purchases(user_id,purchase_no,purchase_date,supplier_id,supplier_name,items_json,subtotal,gst_amount,total,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10) RETURNING id`,[req.user.id,b.purchaseNo||`PUR-${Date.now().toString().slice(-6)}`,b.purchaseDate||dateISO(),b.supplierId||null,b.supplierName||'',JSON.stringify(items),subtotal,gst,total,b.status||'received']));for(const it of items)if(it.productId){await q('UPDATE products SET stock=stock+$1 WHERE id=$2 AND user_id=$3 AND track_stock=TRUE',[n(it.qty),it.productId,req.user.id]);await q('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,it.productId,n(it.qty),'purchase',b.purchaseNo||'Purchase'])}res.status(201).json({id:Number(i.id),total})});

// Dashboard / reports / search / activity
app.get('/api/dashboard',auth,async(req,res)=>{const invoices=rows(await q('SELECT status,total FROM invoices WHERE user_id=$1',[req.user.id])),expenses=rows(await q('SELECT amount FROM expenses WHERE user_id=$1',[req.user.id])),products=rows(await q('SELECT stock,low_stock_threshold,track_stock FROM products WHERE user_id=$1',[req.user.id])),customers=Number(row(await q('SELECT COUNT(*)::int c FROM customers WHERE user_id=$1',[req.user.id])).c),revenue=invoices.filter(x=>x.status==='paid').reduce((a,x)=>a+n(x.total),0),outstanding=invoices.filter(x=>['unpaid','overdue','partial'].includes(x.status)).reduce((a,x)=>a+n(x.total),0),totalExpenses=expenses.reduce((a,x)=>a+n(x.amount),0),lowStock=products.filter(x=>x.track_stock&&n(x.stock)<=n(x.low_stock_threshold)).length,recent=rows(await q('SELECT type,title,meta,created_at FROM activity WHERE user_id=$1 ORDER BY id DESC LIMIT 8',[req.user.id]));res.json({customers,products:products.length,invoices:invoices.length,revenue,outstanding,totalExpenses,profitEstimate:revenue-totalExpenses,lowStock,recent})});
app.get('/api/reports/summary',auth,async(req,res)=>{const r=await q(`SELECT to_char(m,'YYYY-MM') month,COALESCE((SELECT SUM(total) FROM invoices WHERE user_id=$1 AND invoice_date>=m AND invoice_date<m+interval '1 month' AND status='paid'),0) sales,COALESCE((SELECT SUM(amount) FROM expenses WHERE user_id=$1 AND expense_date>=m AND expense_date<m+interval '1 month'),0) expenses FROM generate_series(date_trunc('month',CURRENT_DATE)-interval '5 months',date_trunc('month',CURRENT_DATE),interval '1 month') m ORDER BY m`,[req.user.id]);res.json({months:rows(r)})});
app.get('/api/activity',auth,async(req,res)=>res.json({activity:rows(await q('SELECT type,title,meta,created_at FROM activity WHERE user_id=$1 ORDER BY id DESC LIMIT 50',[req.user.id]))}));
app.get('/api/search',auth,async(req,res)=>{const t=`%${String(req.query.q||'').trim()}%`;const [c,p,i]=await Promise.all([q('SELECT id,name,phone FROM customers WHERE user_id=$1 AND (name ILIKE $2 OR phone ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t]),q('SELECT id,name,sku FROM products WHERE user_id=$1 AND (name ILIKE $2 OR sku ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t]),q('SELECT id,invoice_no,customer_name,total,status FROM invoices WHERE user_id=$1 AND (invoice_no ILIKE $2 OR customer_name ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t])]);res.json({customers:rows(c),products:rows(p),invoices:rows(i)})});

// Razorpay Payment Links integration. Requires RAZORPAY_KEY_ID/SECRET in Render.
app.post('/api/integrations/razorpay/payment-link',auth,async(req,res)=>{const key=process.env.RAZORPAY_KEY_ID,secret=process.env.RAZORPAY_KEY_SECRET;if(!key||!secret)return res.status(503).json({error:'Razorpay is not configured yet. Add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in Render.'});const b=req.body||{},amount=moneyInt(b.amount);if(amount<100)return res.status(400).json({error:'Amount must be at least ₹1.'});const reference=String(b.referenceId||`BIZ-${Date.now()}`).slice(0,40);try{const resp=await fetch('https://api.razorpay.com/v1/payment_links',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Basic '+Buffer.from(`${key}:${secret}`).toString('base64')},body:JSON.stringify({amount,currency:'INR',reference_id:reference,description:String(b.description||'BizKit payment'),customer:{name:String(b.customerName||'Customer'),contact:String(b.customerPhone||''),email:String(b.customerEmail||'')},notify:{sms:false,email:false},reminder_enable:true})});const data=await resp.json();if(!resp.ok)return res.status(resp.status).json({error:data?.error?.description||'Razorpay payment link creation failed'});res.json({id:data.id,short_url:data.short_url,status:data.status})}catch(e){res.status(502).json({error:'Unable to reach Razorpay'})}});

app.get('/api/integrations/status',auth,async(req,res)=>res.json({razorpay:Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),whatsapp:Boolean(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID),email:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER)}));
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'BizKit',version:'0.6.0',database:'postgresql',features:['dashboard','invoices','quotations','customers','products','inventory','suppliers','purchases','payments','expenses','reports','search','razorpay-adapter']})}catch(e){res.status(503).json({ok:false,error:'Database unavailable'})}});

// Page routes
for(const p of ['','/','/features','/pricing','/resources','/login','/signup','/app','/app/invoices','/app/invoices/new','/app/quotations','/app/customers','/app/products','/app/purchases','/app/payments','/app/expenses','/app/reports','/app/tools','/app/settings','/app/integrations']){
  app.get(p,(req,res)=>res.sendFile(path.join(__dirname,'public','app.html')))
}
app.use((req,res)=>res.status(404).sendFile(path.join(__dirname,'public','404.html')));
initDb().then(()=>app.listen(PORT,()=>console.log(`BizKit 0.6.0 running on port ${PORT}`))).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
