app.delete('/api/invoices/:id',auth,async(req,res)=>{try{await withTransaction(async client=>{const inv=(await client.query('SELECT * FROM invoices WHERE id=$1 AND user_id=$2 FOR UPDATE',[req.params.id,req.user.id])).rows[0];if(!inv)throw Object.assign(new Error('Invoice not found'),{status:404});const payments=n((await client.query('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE invoice_id=$1 AND user_id=$2',[req.params.id,req.user.id])).rows[0].total);if(payments>0)throw Object.assign(new Error('Paid invoices cannot be deleted. Reverse or reconcile the payment first.'),{status:400});for(const it of (Array.isArray(inv.items_json)?inv.items_json:[]))if(it.productId){const p=(await client.query('SELECT id,track_stock FROM products WHERE id=$1 AND user_id=$2 FOR UPDATE',[it.productId,req.user.id])).rows[0];if(p?.track_stock){await client.query('UPDATE products SET stock=stock+$1 WHERE id=$2 AND user_id=$3',[n(it.qty),it.productId,req.user.id]);await client.query('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,it.productId,n(it.qty),'invoice_delete',inv.invoice_no])}}await client.query('DELETE FROM invoices WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);});await logActivity(req.user.id,'invoice','Invoice deleted',{id:req.params.id});res.json({ok:true})}catch(e){res.status(e.status||500).json({error:e.message||'Could not delete invoice'})}});
// Quotations
app.get('/api/quotations',auth,async(req,res)=>res.json({quotations:rows(await q('SELECT * FROM quotations WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).map(r=>({...r,items:r.items_json}))}));
app.post('/api/quotations',auth,async(req,res)=>{const b=req.body||{},c=calcDoc(b),i=row(await q(`INSERT INTO quotations(user_id,quote_no,quote_date,valid_until,customer_id,customer_name,customer_phone,customer_address,gst_rate,discount,items_json,subtotal,gst_amount,total,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,$15,$16) RETURNING id`,[req.user.id,b.quoteNo||`QUO-${Date.now().toString().slice(-6)}`,b.quoteDate||dateISO(),b.validUntil||null,b.customerId||null,b.customerName||'',b.customerPhone||'',b.customerAddress||'',c.gstRate,c.discount,JSON.stringify(c.items),c.subtotal,c.gstAmount,c.total,b.status||'draft',b.notes||'']));res.status(201).json({id:Number(i.id),total:c.total})});
app.patch('/api/quotations/:id/status',auth,async(req,res)=>{const allowed=['draft','sent','accepted','rejected','expired'];const status=allowed.includes(req.body?.status)?req.body.status:'draft';await q('UPDATE quotations SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3',[status,req.params.id,req.user.id]);res.json({ok:true})});
app.delete('/api/quotations/:id',auth,async(req,res)=>{await q('DELETE FROM quotations WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

app.post('/api/quotations/:id/convert-to-invoice',auth,async(req,res)=>{try{const result=await withTransaction(async client=>{const quote=(await client.query('SELECT * FROM quotations WHERE id=$1 AND user_id=$2 FOR UPDATE',[req.params.id,req.user.id])).rows[0];if(!quote)throw Object.assign(new Error('Quotation not found'),{status:404});if(['rejected','expired'].includes(quote.status))throw Object.assign(new Error('This quotation cannot be converted'),{status:400});const items=Array.isArray(quote.items_json)?quote.items_json:[];if(!items.length)throw Object.assign(new Error('Quotation has no items'),{status:400});const invoiceNo='INV-Q'+String(quote.quote_no).replace(/[^A-Za-z0-9]/g,'').slice(-16);const duplicate=(await client.query('SELECT id FROM invoices WHERE user_id=$1 AND invoice_no=$2 LIMIT 1',[req.user.id,invoiceNo])).rows[0];if(duplicate)throw Object.assign(new Error('An invoice was already created from this quotation'),{status:409});for(const it of items)if(it.productId){const p=(await client.query('SELECT stock,track_stock FROM products WHERE id=$1 AND user_id=$2 FOR UPDATE',[it.productId,req.user.id])).rows[0];if(!p)throw Object.assign(new Error('Product not found'),{status:400});if(p.track_stock&&n(p.stock)<n(it.qty))throw Object.assign(new Error('Insufficient stock for '+String(it.name||'item')),{status:400});}const ins=(await client.query(`INSERT INTO invoices(user_id,invoice_no,invoice_date,due_date,customer_id,customer_name,customer_phone,customer_address,gst_rate,discount,items_json,subtotal,gst_amount,total,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,'unpaid',$15) RETURNING id`,[req.user.id,invoiceNo,dateISO(),null,quote.customer_id,quote.customer_name||'',quote.customer_phone||'',quote.customer_address||'',quote.gst_rate,quote.discount,JSON.stringify(items),quote.subtotal,quote.gst_amount,quote.total,'Converted from '+quote.quote_no])).rows[0];for(const it of items)if(it.productId){await client.query('UPDATE products SET stock=stock-$1 WHERE id=$2 AND user_id=$3 AND track_stock=TRUE',[it.qty,it.productId,req.user.id]);await client.query('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,it.productId,-it.qty,'sale',invoiceNo])}await client.query("UPDATE quotations SET status='accepted',updated_at=NOW() WHERE id=$1 AND user_id=$2",[quote.id,req.user.id]);return ins});await logActivity(req.user.id,'invoice','Invoice created from quotation',{id:result.id,quotationId:req.params.id});res.status(201).json({id:Number(result.id)})}catch(e){res.status(e.status||500).json({error:e.message||'Could not convert quotation'})}});
// Payments
app.get('/api/payments',auth,async(req,res)=>res.json({payments:rows(await q('SELECT p.*,i.invoice_no,c.name AS customer_name FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id LEFT JOIN customers c ON c.id=p.customer_id WHERE p.user_id=$1 ORDER BY p.id DESC',[req.user.id]))}));
app.post('/api/payments',auth,async(req,res)=>{const b=req.body||{},amount=n(b.amount),invoiceId=b.invoiceId||null,customerId=b.customerId||null;if(amount<=0)return res.status(400).json({error:'Payment amount is required'});const allowed=['UPI','Bank transfer','Cash','Card','Cheque','Other'];if(b.method&&!allowed.includes(b.method))return res.status(400).json({error:'Invalid payment method'});try{const result=await withTransaction(async client=>{let inv=null;if(invoiceId){inv=(await client.query('SELECT id,total,customer_id FROM invoices WHERE id=$1 AND user_id=$2 FOR UPDATE',[invoiceId,req.user.id])).rows[0];if(!inv)throw Object.assign(new Error('Invoice not found'),{status:400});}if(customerId){const customer=(await client.query('SELECT id FROM customers WHERE id=$1 AND user_id=$2',[customerId,req.user.id])).rows[0];if(!customer)throw Object.assign(new Error('Customer not found'),{status:400});if(inv?.customer_id&&String(inv.customer_id)!==String(customerId))throw Object.assign(new Error('Payment customer does not match the invoice customer'),{status:400});}if(!invoiceId&&!customerId)throw Object.assign(new Error('Invoice or customer is required'),{status:400});if(inv){const paid=n((await client.query('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE invoice_id=$1 AND user_id=$2',[invoiceId,req.user.id])).rows[0].total);if(amount>Math.max(0,n(inv.total)-paid)+0.01)throw Object.assign(new Error('Payment exceeds the remaining invoice balance'),{status:400});}const ins=(await client.query('INSERT INTO payments(user_id,invoice_id,customer_id,amount,method,reference,paid_at,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[req.user.id,invoiceId,customerId,amount,b.method||'Cash',String(b.reference||'').trim(),b.paidAt||dateISO(),String(b.note||'').trim()])).rows[0];if(inv){const paid=n((await client.query('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE invoice_id=$1 AND user_id=$2',[invoiceId,req.user.id])).rows[0].total);const status=paid+0.01>=n(inv.total)?'paid':'partial';await client.query('UPDATE invoices SET status=$1,updated_at=NOW() WHERE id=$2 AND user_id=$3',[status,invoiceId,req.user.id]);}return ins});await logActivity(req.user.id,'payment','Payment recorded',{id:result.id,invoiceId,customerId,amount});res.status(201).json({id:Number(result.id)})}catch(e){res.status(e.status||500).json({error:e.message||'Could not record payment'})}});
// Expenses
app.get('/api/expenses',auth,async(req,res)=>res.json({expenses:rows(await q('SELECT * FROM expenses WHERE user_id=$1 ORDER BY id DESC',[req.user.id]))}));
app.post('/api/expenses',auth,async(req,res)=>{const b=req.body||{};if(!b.category||n(b.amount)<=0)return res.status(400).json({error:'Category and amount are required'});const i=row(await q('INSERT INTO expenses(user_id,expense_date,category,amount,note) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.user.id,b.expenseDate||dateISO(),b.category,n(b.amount),b.note||'']));await logActivity(req.user.id,'expense','Expense added',{id:i.id,amount:n(b.amount)});res.status(201).json({id:Number(i.id)})});
app.delete('/api/expenses/:id',auth,async(req,res)=>{await q('DELETE FROM expenses WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});

// Purchases
app.get('/api/purchases',auth,async(req,res)=>res.json({purchases:rows(await q('SELECT * FROM purchases WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).map(r=>({...r,items:r.items_json}))}));
app.post('/api/purchases',auth,async(req,res)=>{const b=req.body||{},items=Array.isArray(b.items)?b.items:[],subtotal=items.reduce((a,x)=>a+n(x.qty)*n(x.rate),0),gst=subtotal*n(b.gstRate)/100,total=subtotal+gst;if(!b.purchaseNo||!b.supplierName||!items.length)return res.status(400).json({error:'Purchase number, supplier and at least one item are required'});if(n(b.gstRate)<0||n(b.gstRate)>100)return res.status(400).json({error:'Invalid GST rate'});if(items.some(x=>n(x.qty)<=0||n(x.rate)<0))return res.status(400).json({error:'Purchase quantities and rates must be valid'});const duplicate=await row(await q('SELECT id FROM purchases WHERE user_id=$1 AND purchase_no=$2 LIMIT 1',[req.user.id,String(b.purchaseNo).trim()]));if(duplicate)return res.status(409).json({error:'Purchase number already exists'});if(b.supplierId){const supplier=row(await q('SELECT id FROM suppliers WHERE id=$1 AND user_id=$2',[b.supplierId,req.user.id]));if(!supplier)return res.status(400).json({error:'Supplier not found'})}const result=await withTransaction(async client=>{for(const it of items)if(it.productId){const p=(await client.query('SELECT id FROM products WHERE id=$1 AND user_id=$2 FOR UPDATE',[it.productId,req.user.id])).rows[0];if(!p)throw Object.assign(new Error('Product not found'),{status:400});}const ins=(await client.query(`INSERT INTO purchases(user_id,purchase_no,purchase_date,supplier_id,supplier_name,items_json,subtotal,gst_amount,total,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10) RETURNING id`,[req.user.id,String(b.purchaseNo).trim(),b.purchaseDate||dateISO(),b.supplierId||null,String(b.supplierName).trim(),JSON.stringify(items),subtotal,gst,total,b.status||'received']));for(const it of items)if(it.productId){await client.query('UPDATE products SET stock=stock+$1 WHERE id=$2 AND user_id=$3 AND track_stock=TRUE',[n(it.qty),it.productId,req.user.id]);await client.query('INSERT INTO stock_movements(user_id,product_id,quantity,type,note) VALUES($1,$2,$3,$4,$5)',[req.user.id,it.productId,n(it.qty),'purchase',String(b.purchaseNo).trim()||'Purchase'])}return ins.rows[0]});await logActivity(req.user.id,'purchase','Purchase recorded',{id:result.id,purchaseNo:String(b.purchaseNo).trim(),total});res.status(201).json({id:Number(result.id),total})});// Dashboard / reports / search / activity
app.get('/api/dashboard',auth,async(req,res)=>{const invoices=rows(await q('SELECT i.id,i.status,i.total,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.invoice_id=i.id AND p.user_id=i.user_id),0) paid FROM invoices i WHERE i.user_id=$1',[req.user.id])),expenses=rows(await q('SELECT amount FROM expenses WHERE user_id=$1',[req.user.id])),products=rows(await q('SELECT stock,low_stock_threshold,track_stock FROM products WHERE user_id=$1',[req.user.id])),customers=Number(row(await q('SELECT COUNT(*)::int c FROM customers WHERE user_id=$1',[req.user.id])).c),revenue=invoices.filter(x=>x.status==='paid').reduce((a,x)=>a+n(x.total),0),outstanding=invoices.filter(x=>['unpaid','overdue','partial'].includes(x.status)).reduce((a,x)=>a+Math.max(0,n(x.total)-n(x.paid)),0),totalExpenses=expenses.reduce((a,x)=>a+n(x.amount),0),lowStock=products.filter(x=>x.track_stock&&n(x.stock)<=n(x.low_stock_threshold)).length,recent=rows(await q('SELECT type,title,meta,created_at FROM activity WHERE user_id=$1 ORDER BY id DESC LIMIT 8',[req.user.id]));res.json({customers,products:products.length,invoices:invoices.length,revenue,outstanding,totalExpenses,profitEstimate:revenue-totalExpenses,lowStock,recent})});
app.get('/api/reports/summary',auth,async(req,res)=>{const r=await q(`SELECT to_char(m,'YYYY-MM') month,COALESCE((SELECT SUM(total) FROM invoices WHERE user_id=$1 AND invoice_date>=m AND invoice_date<m+interval '1 month' AND status='paid'),0) sales,COALESCE((SELECT SUM(amount) FROM expenses WHERE user_id=$1 AND expense_date>=m AND expense_date<m+interval '1 month'),0) expenses FROM generate_series(date_trunc('month',CURRENT_DATE)-interval '5 months',date_trunc('month',CURRENT_DATE),interval '1 month') m ORDER BY m`,[req.user.id]);res.json({months:rows(r)})});
app.get('/api/activity',auth,async(req,res)=>res.json({activity:rows(await q('SELECT type,title,meta,created_at FROM activity WHERE user_id=$1 ORDER BY id DESC LIMIT 50',[req.user.id]))}));
app.get('/api/search',auth,async(req,res)=>{const t=`%${String(req.query.q||'').trim()}%`;const [c,p,i]=await Promise.all([q('SELECT id,name,phone FROM customers WHERE user_id=$1 AND (name ILIKE $2 OR phone ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t]),q('SELECT id,name,sku FROM products WHERE user_id=$1 AND (name ILIKE $2 OR sku ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t]),q('SELECT id,invoice_no,customer_name,total,status FROM invoices WHERE user_id=$1 AND (invoice_no ILIKE $2 OR customer_name ILIKE $2) ORDER BY id DESC LIMIT 8',[req.user.id,t])]);res.json({customers:rows(c),products:rows(p),invoices:rows(i)})});

// Razorpay Payment Links integration. Requires RAZORPAY_KEY_ID/SECRET in Render.
app.post('/api/integrations/razorpay/payment-link',auth,async(req,res)=>{const key=process.env.RAZORPAY_KEY_ID,secret=process.env.RAZORPAY_KEY_SECRET;if(!key||!secret)return res.status(503).json({error:'Razorpay is not configured yet. Add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET in Render.'});const b=req.body||{},amount=moneyInt(b.amount);if(amount<100)return res.status(400).json({error:'Amount must be at least ₹1.'});const reference=String(b.referenceId||`BIZ-${Date.now()}`).slice(0,40);try{const resp=await fetch('https://api.razorpay.com/v1/payment_links',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Basic '+Buffer.from(`${key}:${secret}`).toString('base64')},body:JSON.stringify({amount,currency:'INR',reference_id:reference,description:String(b.description||'BizKit payment'),customer:{name:String(b.customerName||'Customer'),contact:String(b.customerPhone||''),email:String(b.customerEmail||'')},notify:{sms:false,email:false},reminder_enable:true})});const data=await resp.json();if(!resp.ok)return res.status(resp.status).json({error:data?.error?.description||'Razorpay payment link creation failed'});res.json({id:data.id,short_url:data.short_url,status:data.status})}catch(e){res.status(502).json({error:'Unable to reach Razorpay'})}});

app.get('/api/integrations/status',auth,async(req,res)=>res.json({razorpay:Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),whatsapp:Boolean(process.env.WHATSAPP_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID),email:Boolean(process.env.SMTP_HOST&&process.env.SMTP_USER)}));
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'BizKit',version:'0.6.1',database:'postgresql',features:['dashboard','invoices','quotations','customers','products','inventory','suppliers','purchases','payments','expenses','reports','search','razorpay-adapter']})}catch(e){res.status(503).json({ok:false,error:'Database unavailable'})}});

// Page routes
const PAGE_FILES={'/':'home.html','/features':'features.html','/pricing':'pricing.html','/resources':'resources.html','/login':'login.html','/signup':'signup.html','/app':'dashboard.html','/app/invoices':'invoices.html','/app/invoices/new':'invoice-new.html','/app/quotations':'quotations.html','/app/customers':'customers.html','/app/products':'products.html','/app/purchases':'purchases.html','/app/payments':'payments.html','/app/expenses':'expenses.html','/app/reports':'reports.html','/app/tools':'tools.html','/app/settings':'settings.html','/app/integrations':'integrations.html'};
for(const [route,file] of Object.entries(PAGE_FILES)) app.get(route,(req,res)=>res.sendFile(path.join(ASSET_ROOT,'pages',file)));
app.use((req,res)=>res.status(404).sendFile(path.join(ASSET_ROOT,'404.html')));
initDb().then(()=>app.listen(PORT,()=>console.log(`BizKit 0.6.1 running on port ${PORT}`))).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
